# Use official Node.js image as base
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies separately (caches layers)
COPY package.json package-lock.json* ./
RUN npm install

# Copy rest of the app
COPY . .

# Build the Next.js app
# RUN npm run build

# Expose port
EXPOSE 3000

# Start Next.js
CMD ["npm", "run", "dev"]
